name: cntk-py27
channels:
- defaults
# For imageio and dlib:
- conda-forge
dependencies:
- h5py
- jupyter
- matplotlib
- mock
- numpy
- pandas
# Downgrade to 0.5.0 due to https://github.com/pydata/pandas-datareader/issues/495
- pandas-datareader==0.5.0
- pandoc
- pip
- python==2.7.15
- pyyaml
- scipy
- seaborn
- setuptools
- six
- wheel
- cython
- dlib
- pip:
  - easydict
  - gym
  - keras==2.0.6
  - pydot-ng
  - pygame
  - pytest==3.5.1
  - sphinx-rtd-theme
  - sphinx
  - nbsphinx
  - twine
  - protobuf
  - pillow
  - imageio
  - scikit-image
  - scikit-learn